Repository alphagov/forms-prototypes, pull requests merged in 2024-03, with the labels that each got.

#222 Organisation Admin Journey
  app/views/product-pages/Group-admin/creategroup.html
  app/views/product-pages/Group-admin/editmembers.html
  app/views/product-pages/Group-admin/features.html
  app/views/product-pages/Group-admin/get-started.html
  app/views/product-pages/Group-admin/group.html
  app/views/product-pages/Group-admin/grouplanding.html
  app/views/product-pages/Group-admin/index.html
  app/views/product-pages/Group-admin/next.html
  app/views/product-pages/Group-admin/requirements.html
Labels: user research

#225 2024 03 20 group org admin view quick fixes
  app/views/product-pages/Group-admin/creategroup.html
  app/views/product-pages/Group-admin/group.html
  app/views/product-pages/Group-admin/grouplanding.html
  app/views/product-pages/org-admin/creategroup.html
  app/views/product-pages/org-admin/editmembers.html
  app/views/product-pages/org-admin/features.html
  app/views/product-pages/org-admin/get-started.html
  app/views/product-pages/org-admin/group.html
  app/views/product-pages/org-admin/grouplanding.html
  app/views/product-pages/org-admin/index.html
  app/views/product-pages/org-admin/next.html
  app/views/product-pages/org-admin/requirements.html
  index.html
Labels: bug

#216 2024 02 01 payment link testing screens
  app/assets/sass/application.scss
  app/routes.js
  app/views/form-designer/pages/_routes.js
  app/views/form-designer/pages/confirmation/view.html
  app/views/form-designer/pages/edit-answer-type.html
  app/views/form-designer/pages/preview.html
  app/views/form-designer/partials/status-draft-form.html
  app/views/form-designer/payment/add-payment-link.html
  app/views/form-designer/payment/payment-link-example.html
  app/views/form-designer/preview/confirmation.html
  app/views/form-designer/preview/page.html
Labels: user research, iteration

#237 Content and link changes for group + org admin journeys
  app/views/product-pages/_routes.js
  app/views/product-pages/group-admin/editmembers3.html
  app/views/product-pages/group-admin/editmembers4.html
  app/views/product-pages/group-admin/grouplanding2.html
  app/views/product-pages/org-admin/add-groupadmin-and-editor.html
  app/views/product-pages/org-admin/editmembers.html
  app/views/product-pages/org-admin/editmembers2.html
  app/views/product-pages/org-admin/editmembers3.html
  app/views/product-pages/org-admin/editmembers4.html
  app/views/product-pages/org-admin/grouplanding2.html
  app/views/product-pages/org-admin/licencingforms.html
  app/views/product-pages/org-admin/licencingforms2.html
Labels: iteration

#239 Do not merge] 27.03.2024 content changes
  app/views/product-pages/org-admin/editmembers.html
  app/views/product-pages/org-admin/editmembers2.html
  app/views/product-pages/org-admin/editmembers3.html
  app/views/product-pages/org-admin/editmembers4.html
  app/views/product-pages/org-admin/editmembers5.html
  app/views/product-pages/org-admin/licencingforms.html
  app/views/product-pages/org-admin/upgrade.html
  app/views/product-pages/org-admin/upgrade2.html
Labels: iteration

#240 content changes
  app/views/product-pages/group-admin/editmembers2.html
  app/views/product-pages/group-admin/editmembers3.html
  app/views/product-pages/group-admin/editmembers4.html
  app/views/product-pages/org-admin/allusers.html
Labels: iteration
